# Schema for the configuration files of the Linkedin posts module.
linkedin_posts.settings:
  type: config_object
  label: 'Linkedin posts settings'
  mapping:
    organization_id:
      type: string
      label: 'Company ID'
    client_id:
      type: string
      label: 'Client Id'
    client_secret:
      type: string
      label: 'Client secret'
